### ISSUE TITLE
Path to cover image and logo

### ISSUE THREAD

**Issue by armaneshaghi** [SenjinDarashiva/hugo-uno#16]
First thank you for this open-source theme. 

I'm trying to use `hugo-uno` with `hugo` for the very first time, and I would appreciate if you could bear with me:

The problem is I can successfully publish `hugo` website to public folder with hugo-uno theme, I can see the same style of fonts and etc as your own example. The only problem is that after replacing my own cover inside `public/images/my-new-cover.jpg` , cover image does not show at all. 

My question is what would be the best way to replace logo and cover image with that of my own?

![screenshot](https://cloud.githubusercontent.com/assets/4290297/8774167/310df29a-2ed3-11e5-9293-60c3eeba790c.png)

**Comment by SenjinDarashiva** [comment]
Hi, try to either rename the new background to `background-cover.jpg` or change the cover path in your config.toml, with that alteration the config in the readme should look like this:
```
languageCode = "en-us"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseurl = "http://fredrikloch.me/"
canonifyurls = true
title = "Fredrik Loch"
author = "Fredrik Loch"

[indexes]
   category = "categories"
   tag = "tags"
[Params]
  Subtitle = "Spinning the cogs in the widgets"
  AuthorName = "Fredrik"
  github = "Senjindarashiva"
  bitbucket = "floch"
  flickr = "senjin"
  twitter = "senjindarshiva"
  email = "fredrik.loch@outlook.com"
  description = ""
  cv = "/pages/cv"
  linkedin = "fredrikloch"
  cover = "/images/my-new-cover.jpg"
  logo = "/img/logo-1.jpg"
```

**Comment by armaneshaghi** [comment]
Thanks, I have tried this, but still do not get anything. After changing `config.toml` I proceed with both `hugo server --watch` and then `hugo` to publish. Both of which do not show any background at all.

```
  1 languageCode = "en-us"
  2 #theme = "hugo-uno"
  3 contentdir = "content"
  4 publishdir = "public"
  5 builddrafts = false
  6 baseurl = "http://www.homepages.ucl.ac.uk/~skgtaes/"
  7 canonifyurls = true
  8 title = "Arman Eshaghi"
  9 author = "Arman Eshaghi"
 10 copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
 11 
 12 
 13 [indexes]
 14    category = "categories"
 15    tag = "tags"
 16 [Params]                                                                                                                                                                                                                                 
 17   AuthorName = "Arman"
 18   github = "armaneshaghi"
 19   twitter = "es_arman"
 20   email = "arman.eshaghi.14@xxx"
 21   description = "PhD Student at the UCL Institute of Neurology"
 22   cv = "/pages/cv"
 23   cover = "/images/new_background.jpg"
 24   logo = "/img/logo-1.jpg"
```

**Comment by SenjinDarashiva** [comment]
I think this could be caused by hugo not moving your `images` folder to it's publish location, try and copy the entire images folder into a folder named static at your site root.

**Comment by armaneshaghi** [comment]
Thanks so much!
