### ISSUE TITLE
Edit Landing Page

### ISSUE THREAD

**Issue by benny-noh** [SenjinDarashiva/hugo-uno#22]
Really nice theme. I use it at my really new hugo blog under dev.hagels.net but I can not find any option to edit the subtitle on the landing page. I started yesterday with hugo and migrated my wordpress blog to hugo today. So I am really new to hugo but I searched for two hours now and can not find the point where I can edit this part of the coverpage.

Could you please help! =)

**Comment by SenjinDarashiva** [comment]
It should be possible to change by altering the parameter "description" in the yaml config file

**Comment by benny-noh** [comment]
Tried this already and tried it just now again but the subtitle does not
change. had restarted Hugo server after changing description but still
showing the default subtitle. any other idea?
Am 01.02.2016 11:50 schrieb "Fredrik" <notifications@github.com>:

**Comment by tcbtcb** [comment]
@benny-noh - the variable you want is in the partials/sidebar.html file. It's set to {{ Site.Params.description }} so the variable `description` needs to be set in the Params section of the config file. Once that is set it should be fine. Works for me at least.

**Comment by benny-noh** [comment]
Yes! Now it works. Thanks for the hint :)
Am 01.02.2016 20:32 schrieb "Thad Brown" <notifications@github.com>:

**Comment by SenjinDarashiva** [comment]
Thanks @tcbtcb :) and im glad it worked out
